filter:
  dependency_paths: [vendor/]
checks:
  php: true
build:
  environment:
    php:
      pecl_extensions: [zip]
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
